version: "3.8"
services:
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8888:8888"
    depends_on:
      eureka-server:
        condition: service_healthy

  project-service:
    build:
      context: ./project-service
    ports:
      - "8081:8081"
    depends_on:
      - projectdb

  resource-service:
    build:
      context: ./resource-service
    ports:
      - "8082:8082"
    depends_on:
      - resourcedb

  task-service:
    build:
      context: ./task-service
    ports:
      - "8083:8083"
    depends_on:
      - taskdb

  user-service:
    build:
      context: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - userdb

  projectdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: project_db_2
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - project-db:/var/lib/mysql

  resourcedb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: resource_db_2
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - resource-db:/var/lib/mysql

  taskdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: task_db_2
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - task-db:/var/lib/mysql

  userdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: user_db_2
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - user-db:/var/lib/mysql

volumes:
  project-db:
  resource-db:
  task-db:
  user-db: