server:
  port: 8082

spring:
  application:
    name: task-service
  datasource:
#    url: jdbc:mysql://taskdb:3306/task_db_1?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/task_db_1?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true